apiVersion: adaptdl.petuum.com/v1
kind: AdaptDLJob
metadata:
  generateName: mit-
spec:
  template:
    spec:
      containers:
      - name: main
        command:
        - python3
        - /root/imagenet/main.py
        - --arch=resnet50
        - --classes=365
        - --batch-size=200
        - --lr=0.008
        - --epochs=6
        - --autoscale-bsz
#        - /mnt/mit
#        - /data/mit
        - /juicefs/mit
        env:
        - name: PYTHONUNBUFFERED
          value: "true"
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 2
            memory: "8G"
          requests:
            nvidia.com/gpu: 1
            cpu: 2
            memory: "8G"
        volumeMounts:
        - name: data
          mountPath: /mnt
          readOnly: true
        - name: data-ssd
          mountPath: /data
          readOnly: true
        - name: juicefs
          mountPath: /juicefs
          readOnly: true
      volumes:
      - name: data
        hostPath:
          path: /mnt
          type: Directory
      - name: data-ssd
        hostPath:
          path: /data
          type: Directory
      - name: juicefs
        hostPath:
          path: /juicefs
          type: Directory
      imagePullSecrets:
      - name: regcred
